### POST patient request
POST http://localhost:8084/api/patients
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Alex Boiko",
  "email": "bxcv46@gmail.com",
  "address": "152 Saf eEfjn",
  "dateOfBirth": "1985-10-28",
  "registerDate": "2025-10-10"
}

###